In [7]:
import torch
print(torch.__version__)

2.13.0+cu126


In [8]:
if torch.cuda.is_available():
    print("CUDA is available. You can use GPU acceleration.")
else:
    print("CUDA is not available. You will be using CPU.")

CUDA is available. You can use GPU acceleration.


###  Tensor

***creating tensors***

In [11]:
tensor=torch.empty(3, 4)
type(tensor)

torch.Tensor

In [16]:
tensor_zeros=torch.zeros(3,4)
tensor_ones=torch.ones(3,4)

print(tensor_zeros) 
print(tensor_ones)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [17]:
torch.rand(3,4)

tensor([[0.8769, 0.3846, 0.6518, 0.8238],
        [0.3574, 0.8725, 0.1038, 0.2857],
        [0.5233, 0.8924, 0.2180, 0.4114]])

***use of seed***

seed ensures to produce same numbers everytime when rand function is called with the exact seed value

In [18]:
torch.manual_seed(42)  # Set a random seed for reproducibility
torch.rand(3,4)  # Generate a random tensor with the same seed

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

In [19]:
torch.manual_seed(42)  # Set a random seed for reproducibility
torch.rand(3,4)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

***creating custom tensor***

In [21]:
torch.tensor([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])

In [27]:
# torch arrange --> ( start, end, step)
torch.arange(0, 10, 2)

#torch.linspace --> ( start, end, number of points)
torch.linspace(0, 1, 5)

# torch.eye --> ( size of the matrix)
torch.eye(3)

#using full
torch.full((3, 4), 7)  # Create a 3x4 tensor filled with the value 7

tensor([[7, 7, 7, 7],
        [7, 7, 7, 7],
        [7, 7, 7, 7]])

### Mathematical Operation

In [32]:
torch.manual_seed(42)  # Set a random seed for reproducibility
a=torch.randn(3, 4)  # Create a random tensor with a normal distribution
b=torch.randn(3, 4)  # Create another random tensor with a normal distribution
print(a)    
print(b)    

tensor([[ 0.3367,  0.1288,  0.2345,  0.2303],
        [-1.1229, -0.1863,  2.2082, -0.6380],
        [ 0.4617,  0.2674,  0.5349,  0.8094]])
tensor([[ 1.1103, -1.6898, -0.9890,  0.9580],
        [ 1.3221,  0.8172, -0.7658, -0.7506],
        [ 1.3525,  0.6863, -0.3278,  0.7950]])


In [33]:
# addition
add_a_b=a + b
print(add_a_b)

tensor([[ 1.4470, -1.5610, -0.7545,  1.1883],
        [ 0.1993,  0.6309,  1.4424, -1.3886],
        [ 1.8142,  0.9537,  0.2071,  1.6043]])


In [34]:
# subtraction
sub_a_b=a - b
print(sub_a_b)

tensor([[-0.7736,  1.8186,  1.2234, -0.7276],
        [-2.4450, -1.0035,  2.9740,  0.1126],
        [-0.8909, -0.4190,  0.8627,  0.0144]])


In [36]:
a=torch.tensor([[1, 2], [3, 4]])

In [37]:
# sum of all elements in the tensor
torch.sum(a)

tensor(10)

In [40]:
# sum of elements along a specific dimension (e.g., rows)
torch.sum(a, dim=1)  # Sum along columns (resulting in a 1D tensor with sums of each row)
torch.sum(a, dim=0)  # Sum along rows (resulting in a 1D tensor with sums of each column)

tensor([4, 6])

In [39]:
# Element-wise addition
a = torch.tensor([[1, 2], [3, 4]])
b = torch.tensor([[5, 6], [7, 8]])
result = a + b  
print(result)  # Output: tensor([[ 6,  8], [10, 12]])

tensor([[ 6,  8],
        [10, 12]])


In [41]:
# argmax and argmin
a = torch.tensor([[1, 2], [3, 4]])
argmax_a = torch.argmax(a)
argmin_a = torch.argmin(a)
print(argmax_a)  # Output: tensor(3)
print(argmin_a)  # Output: tensor(0)

tensor(3)
tensor(0)


In [42]:
# matrix multiplication
torch.manual_seed(42)  # Set a random seed for reproducibility
a = torch.randn(2, 3)  # Create a random tensor of shape (2, 3)
b = torch.randn(3, 4)  # Create another random tensor of shape (3, 4)

result = torch.matmul(a, b)  # Perform matrix multiplication
print(result)  # Output will be a tensor of shape (2, 4)

tensor([[ 0.5805,  0.1141,  0.6084,  0.0640],
        [ 0.0923, -1.2342, -1.3867,  1.8067]])


In [43]:
# dot product
a = torch.tensor([1, 2, 3])
b = torch.tensor([4, 5, 6])

dot_product = torch.dot(a, b)
print(dot_product)  # Output: tensor(32)

tensor(32)


In [44]:
# transpose
a = torch.tensor([[1, 2], [3, 4]])
transposed_a = torch.transpose(a, 0, 1)  # Transpose the tensor
print(transposed_a)  # Output: tensor([[1, 3], [2, 4]])

tensor([[1, 3],
        [2, 4]])


In [45]:
# determinant
a = torch.tensor([[1, 2], [3, 4]], dtype=torch.float32)
det_a = torch.det(a)

print(det_a)  # Output: tensor(-2.)

tensor(-2.)


In [46]:
# inverse
a = torch.tensor([[1, 2], [3, 4]], dtype=torch.float32)
inv_a = torch.inverse(a)

print(inv_a)  # Output: tensor([[-2.0000,  1.0000], [ 1.5000, -0.5000]])

tensor([[-2.0000,  1.0000],
        [ 1.5000, -0.5000]])


In [50]:
# comparisons   
i=torch.tensor([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
j=torch.tensor([[9, 8, 7],[6, 5, 4],[3, 2, 1]])

#greater than
result_gt = i > j
print(result_gt)  # Output: tensor([[False, False, False], [False, False,  True], [ True,  True,  True]])

#less than
result_lt = i < j
print(result_lt)  # Output: tensor([[ True,  True,  True], [ True, False, False], [False, False, False]])

#equal to
result_eq = i == j
print(result_eq)  # Output: tensor([[False, False, False], [False,  True, False], [False, False, False]])

tensor([[False, False, False],
        [False, False,  True],
        [ True,  True,  True]])
tensor([[ True,  True,  True],
        [ True, False, False],
        [False, False, False]])
tensor([[False, False, False],
        [False,  True, False],
        [False, False, False]])


In [57]:
# special functions
a=torch.tensor([[0.5, 1.0, 1.5],[2.0, 2.5, 3.0],[3.5, 4.0, 4.5]])

#log
log_a = torch.log(a)
print(log_a)  # Output: tensor([[-0.6931,  0.0000,  0.4055], [ 0.6931,  0.9163,  1.0986], [ 1.2528,  1.3863,  1.5041]])

#exp
exp_a = torch.exp(a)
print(exp_a)  # Output: tensor([[ 1.6487,  2.7183,  4.4817], [ 7.3891, 12.1825, 20.0855], [33.1155, 54.5982, 90.0171]])

#sigmoid
sigmoid_a = torch.sigmoid(a)
print(sigmoid_a)  # Output: tensor([[0.6225, 0.7311, 0.8176], [0.8808, 0.9241, 0.9526], [0.9707, 0.9820, 0.9890]])

#softmax
softmax_a = torch.softmax(a, dim=1)
print(softmax_a)  # Output: tensor([[0.0900, 0.2447, 0.6652], [0.0900, 0.2447, 0.6652], [0.0900, 0.2447, 0.6652]])

#relu
relu_a = torch.relu(a)
print(relu_a)  # Output: tensor([[0.5000, 1.0000, 1.5000], [2.0000, 2.5000, 3.0000], [3.5000, 4.0000, 4.5000]])

tensor([[-0.6931,  0.0000,  0.4055],
        [ 0.6931,  0.9163,  1.0986],
        [ 1.2528,  1.3863,  1.5041]])
tensor([[ 1.6487,  2.7183,  4.4817],
        [ 7.3891, 12.1825, 20.0855],
        [33.1155, 54.5981, 90.0171]])
tensor([[0.6225, 0.7311, 0.8176],
        [0.8808, 0.9241, 0.9526],
        [0.9707, 0.9820, 0.9890]])
tensor([[0.1863, 0.3072, 0.5065],
        [0.1863, 0.3072, 0.5065],
        [0.1863, 0.3072, 0.5065]])
tensor([[0.5000, 1.0000, 1.5000],
        [2.0000, 2.5000, 3.0000],
        [3.5000, 4.0000, 4.5000]])


In [68]:
#copy tensors
a=torch.tensor([[1, 2], [3, 4]])
b=a.clone()  # Create a copy of tensor 'a'
print(b)  # Output: tensor([[1, 2], [3, 4]])

tensor([[1, 2],
        [3, 4]])


### tensors on gpu

In [61]:
torch.cuda.is_available()

True

In [62]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

In [67]:
a=torch.tensor([[1, 2], [3, 4]], device=device)
a # everything on this tensor will be on the GPU if available, otherwise on the CPU.

tensor([[1, 2],
        [3, 4]], device='cuda:0')

### reshape

In [72]:
# reshaping
A=torch.tensor([[1, 2, 3], [4, 5, 6]])
B=A.reshape(3, 2)  # Reshape tensor 'A' to have 3 rows and 2 columns
print(B)  # Output: tensor([[1, 2], [3, 4], [5, 6]])

c=A.reshape(6)  # Reshape tensor 'A' to have 6 elements in a 1D tensor
print(c)  # Output: tensor([1, 2, 3, 4, 5, 6])

tensor([[1, 2],
        [3, 4],
        [5, 6]])
tensor([1, 2, 3, 4, 5, 6])


In [73]:
# flattening
A = torch.tensor([[1, 2, 3], [4, 5, 6]])
b=A.flatten()  # Flatten the tensor 'A' into a 1D tensor
print(b)  # Output: tensor([1, 2, 3, 4, 5, 6])

tensor([1, 2, 3, 4, 5, 6])


In [80]:
#permute
a=torch.tensor([[[1, 2, 3, 0], [4, 5, 6, 0],[7, 8, 9, 0]],[[10, 11, 12, 0], [13, 14, 15, 0],[16, 17, 18, 0]]])
print(a.shape)  # Output: torch.Size([2, 3, 4])

#a.shape index : 0:2, 1:3, 2:4
permuted_a = a.permute(2, 1, 0)  # Permute the dimensions of the tensor
# in permute, the order of dimensions is changed. The first dimension (index 0) becomes the last dimension (index 2), the second dimension (index 1) becomes the first dimension (index 0), and the third dimension (index 2) becomes the second dimension (index 1).

print(permuted_a.shape)  # Output: torch.Size([4, 3, 2])
print(permuted_a)  # Output: tensor([[[1, 4, 7], [2, 5, 8], [3, 6, 9]], [[10, 13, 16], [11, 14, 17], [12, 15, 18]]])

torch.Size([2, 3, 4])
torch.Size([4, 3, 2])
tensor([[[ 1, 10],
         [ 4, 13],
         [ 7, 16]],

        [[ 2, 11],
         [ 5, 14],
         [ 8, 17]],

        [[ 3, 12],
         [ 6, 15],
         [ 9, 18]],

        [[ 0,  0],
         [ 0,  0],
         [ 0,  0]]])


In [83]:
#unsqueeze --> adding a new dimension to the tensor
a=torch.rand(226,226,3)
b=a.unsqueeze(0)  # Add a new dimension at index 0
print(b.shape)  # Output: torch.Size([1, 226, 226, 3])

torch.Size([1, 226, 226, 3])


In [84]:
# squeeze --> removing a dimension of size 1 from the tensor
a=torch.rand(1, 226, 226, 3)
b=a.squeeze(0)  # Remove the dimension at index 0
print(b.shape)  # Output: torch.Size([226, 226, 3])

torch.Size([226, 226, 3])


## numpy and pytorch

In [87]:
import numpy as np

#pytorch tensor to numpy array
tensor = torch.tensor([[1, 2], [3, 4]])
numpy_array = tensor.numpy()
print(type(numpy_array))  # Output: <class 'numpy.ndarray'>

<class 'numpy.ndarray'>


In [88]:
#numpy array to pytorch tensor
a = np.array([[1, 2], [3, 4]])
tensor_from_numpy = torch.from_numpy(a)
print(type(tensor_from_numpy))  # Output: <class 'torch.Tensor'>

<class 'torch.Tensor'>
